### ISSUE TITLE
Issue keras_federated_classifier.py CPU:0 unknown device

### ISSUE THREAD

**Issue by hahna** [coMindOrg/federated-averaging-tutorials#6]
After I have started the server
 python3 keras_federated_classifier.py --job_name=ps --task_index=0
and the client with
 python3 keras_federated_classifier.py --job_name=worker --task_index=0
I get the following error

Traceback (most recent call last):
  File "keras_federated_classifier.py", line 89, in <module>
    global_step = tf.compat.v1.train.get_or_create_global_step()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/training_util.py", line 161, in get_or_create_global_step
    global_step_tensor = create_global_step(graph)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/training_util.py", line 133, in create_global_step
    ops.GraphKeys.GLOBAL_VARIABLES, ops.GraphKeys.GLOBAL_STEP
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1504, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1247, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 567, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 519, in _true_getter
    aggregation=aggregation)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 937, in _get_single_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 258, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 219, in _variable_v1_call
    shape=shape)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 197, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 2507, in default_variable_creator
    shape=shape)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1406, in __init__
    distribute_strategy=distribute_strategy)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1537, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 906, in <lambda>
    partition_info=partition_info)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/init_ops.py", line 114, in __call__
    return array_ops.zeros(shape, dtype)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2349, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2307, in _constant_if_small
    return constant(value, shape=shape, dtype=dtype, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
RuntimeError: /job:worker/replica:0/task:0/device:CPU:0 unknown device.

I am using python 3.7 and tensorflow 2.0.0 on MacOS Catalina. The error also occurs under Windows 10.

**Comment by jalbertoroman** [comment]
TF 2.0 is not supported by this implementation. If you need production code, contact us at contact@acuratio.com
